// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Result struct {
	ID         int32
	Url        string
	StatusCode int32
	DurationMs int32
	Error      pgtype.Text
	CreatedAt  pgtype.Timestamp
}
